# Generated by Django 4.2.6 on 2023-10-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_images',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.everestkitchenpa.com%2Fassets%2Fpages%2FcoldBeverages.html&psig=AOvVaw2nEno7nxndyhsVySSJ1q_M&ust=1697692327400000&source=images&cd=vfe&ved=0CBIQjhxqFwoTCPix_vPq_oEDFQAAAAAdAAAAABAE', max_length=1000),
        ),
    ]
