# Generated by Django 4.2.6 on 2023-10-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_images',
            field=models.CharField(default='https://cdn.vectorstock.com/i/1000x1000/37/07/fresh-vegetables-with-placeholder-for-text-vector-6263707.webp', max_length=500),
        ),
    ]
